# Generated by Django 4.2.7 on 2024-03-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_alter_problem_is_already_solved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='is_solved_bt_yonsei',
            new_name='is_solved_by_yonsei',
        ),
    ]
